apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polar-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: 24b7f79204fd665bc811ebc9a90c7fd4-41875236.ap-northeast-2.elb.amazonaws.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge-service
                port:
                  number: 80
