apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polar-moviechart/edge-service/k8s?ref=f48b613a6c00639d19672a6d33c6936c4ae64ab1

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: edge-config
  namespace: polar

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: edge-service
  newName: ghcr.io/polar-moviechart/edge-service
  newTag: f48b613a6c00639d19672a6d33c6936c4ae64ab1
- name: movie-service
  newName: ghcr.io/polar-moviechart/movie-service
  newTag: 2cf2ed36683c2b68b8cf448c06f67779daefee88

replicas:
- count: 1
  name: movie-service
