apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polar-moviechart/edge-service/k8s?ref=f48b613a6c00639d19672a6d33c6936c4ae64ab1

configMapGenerator:
  - name: edge-config
    behavior: merge
    files:
      - application.yml
    options:
      labels:
        app: edge-service

patchesStrategicMerge:
  - patch-regcred.yml
  - patch-env.yml

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: edge-service
  newName: ghcr.io/polar-moviechart/edge-service
  newTag: f48b613a6c00639d19672a6d33c6936c4ae64ab1

replicas:
- count: 1
  name: edge-service
