apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- ingress.yml

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: edge-config
  options:
    labels:
      app: edge-service

patches:
- path: patch-regcred.yml
- path: patch-env.yml

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: edge-service
  newName: ghcr.io/polar-moviechart/edge-service
  newTag: 3dec08c9ea26e529c4c1f465b04ea31f8a26e220

replicas:
- count: 1
  name: edge-service
