apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polar-rabbitmq-pvc
  namespace: rabbitmq-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
