apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 'ingress-nginx-controller'에 필요한 권한을 설정
  # (주로 Pod, IngressClass 등을 포함)
  name: ingress-nginx-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]