apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  labels:
    app: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
        - name: ingress-nginx-controller
          image: nginx-ingress-controller:stable-v1.10.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8443
          volumeMounts:
            - name: ingress-nginx-config
              mountPath: /etc/nginx/template
              readOnly: true
            - name: ingress-nginx-proxy
              mountPath: /etc/nginx/proxy
              readOnly: true
            - name: ingress-nginx-ssl
              mountPath: /etc/ssl/certs
              readOnly: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: ingress-nginx-config
          configMap:
            name: ingress-nginx-controller
        - name: ingress-nginx-proxy
          configMap:
            name: ingress-nginx-controller
        - name: ingress-nginx-ssl
          configMap:
            name: ingress-nginx-controller
