# 인그레스는 기본적으로 로드밸런서를 지원하지만, 로컬이나 AWS lightsail에서는
# 로드밸런서의 externalIp를 지정할 수 없기 때문에 NodePort로 변경해준다.
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
    - port: 443
      targetPort: 443
      nodePort: 30443
  externalTrafficPolicy: Local