spring:
  application:
    name: edge-service

  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: http://user-service:8082
          predicates:
            - Path=/public/api/v1/users/**
          filters:
            - JwtAuthFilterOptional

        - id: user-service-secure
          uri: http://user-service:8082
          predicates:
            - Path=/secure/api/v1/users/**
          filters:
            - JwtAuthFilter

        - id: movie-service-public
          uri: http://movie-service:8081
          predicates:
            - Path=/public/api/v1/movies/**
          filters:
            - JwtAuthFilterOptional

        - id: movie-service-secure
          uri: http://movie-service:8081
          predicates:
            - Path=/secure/api/v1/movies/**
          filters:
            - JwtAuthFilter

server:
  port: 8080

kakao:
  client:
    id: 3c46ac9fcd53813acad0147afe8d5a31

jwt:
  secretKey: polarMoviechartJwtSecretPolarMoviechartJwtSecret

management:
  endpoints:
    web:
      exposure:
        #        include: configprops, env, gateway, health, heapdump, info, loggers, mappings, prometheus
        include: gateway, health, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
  metrics:
    tags:
      application: ${spring.application.name}