apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: default
spec:
  secretName: api-tls
  dnsNames:
    - api.polar-moviechart.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer