apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # ACME 서버 URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: stk346@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          # DNS 솔버는 사용하는 DNS 서비스에 맞춰 설정해야 합니다
          route53:
            accessKeyID: YOUR_AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
            region: us-east-1
