# HTTP 서버 (80 포트)
#  server {
#    listen 80;
#    server_name api.polar-moviechart.com;
#
#    client_max_body_size 100M;  # 허용 크기
#
#  # Certbot을 위한 인증서 검증 경로 (리디렉션 제외)
#    location ~ /.well-known/acme-challenge/ {
#        allow all;
#        root /var/www/html;  # Certbot이 인증서를 발급받을 수 있도록 설정
#
#        if ($http_x_forwarded_proto = "https") {
#            return 200;
#        }
#    }
#
##     클라우드플레어가 HTTPS로 전달한 요청을 다시 HTTP로 리다이렉트하지 않도록
#    if ($http_x_forwarded_proto != "https") {
#        return 301 https://$host$request_uri;
#    }
#}

# HTTPS 서버 (443 포트)
server {
    listen 443 ssl;
    server_name api.polar-moviechart.com;

  # SSL 인증서 경로
    ssl_certificate /etc/letsencrypt/live/api.polar-moviechart.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.polar-moviechart.com/privkey.pem;

  # SSL 보안 설정 (필요에 따라 추가 설정 가능)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    
    client_max_body_size 100M;  # 허용 크기
    
    location / {
    proxy_pass http://localhost:31506;  # NodePort로 요청 전달
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
#    proxy_set_header X-Forwarded-Proto https;
    
    # cors 관련 설정
    add_header 'Access-Control-Allow-Origin' 'https://polar-moviechart.com';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type';
    add_header 'Access-Control-Allow-Credentials' 'true';
    }
    
    error_log /var/log/nginx/api-error.log;
    access_log /var/log/nginx/api-access.log;
}
