apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_ACTIVE_PROFILES
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://polar-mysql:3306/polardb_user
            - name: SPRING_DATASOURCE_USER
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "102030"
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "root"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "polar-chart"
          volumeMounts:
            - name: user-config-volume
              mountPath: /workspace/config
      volumes:
        - name: user-config-volume
          configMap:
            name: user-config
