apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polar-moviechart/user-service/k8s?ref=c4b2b8c1964ecf21c93c2ac1817e37594f102030

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: user-config
  namespace: polar

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: user-service
  newName: ghcr.io/polar-moviechart/user-service
  newTag: bfd0cd98fd16fa300bac82aa1b3a404bea26650d

replicas:
- count: 1
  name: user-service
