apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: user-config
  options:
    labels:
      app: user-service

patches:
- path: patch-regcred.yml
- path: patch-env.yml

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: user-service
  newName: ghcr.io/polar-moviechart/user-service
  newTag: b4f21502eefdb221ffa3da2d8d1b4c90906bdcdd

replicas:
- count: 1
  name: user-service
