apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polar-moviechart/user-service/k8s?ref=cf02b4936b4fbd77e44cd882621fae8d46017e4e

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: user-config
  namespace: polar

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: user-service
  newName: ghcr.io/polar-moviechart/user-service
  newTag: cf02b4936b4fbd77e44cd882621fae8d46017e4e

replicas:
- count: 1
  name: user-service
