apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: user-config
  options:
    labels:
      app: user-service

patches:
- path: patch-regcred.yml
- path: patch-env.yml

# kustomize edit set image 명령어에 의해 변경됨
images:
- name: user-service
  newName: ghcr.io/polar-moviechart/user-service
  newTag: de6933d47275b0664c45034f62561da3a119a623

replicas:
- count: 1
  name: user-service
