apiVersion: v1
kind: Service
metadata:
  name: polar-mysql
spec:
  selector:
    app: polar-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006 # 외부에서 접근할 수 있는 포트
  type: NodePort
