global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'edge-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'edge-service:8080' ]
  - job_name: 'movie-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'movie-service:8081' ]
  - job_name: 'user-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:8082' ]
  
