apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/polar-moviechart/polar-deployment.git
    targetRevision: main
    path: kubernetes/applications/edge-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true