apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: movie-service
          image: movie-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_ACTIVE_PROFILES
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://13.125.45.144:30006/polardb_movie
            - name: SPRING_DATASOURCE_USER
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "102030"
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "root"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "polar-chart"
          volumeMounts:
            - name: movie-config-volume
              mountPath: /workspace/config
      volumes:
        - name: movie-config-volume
          configMap:
            name: movie-config

