apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: polar
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
#          image: ghcr.io.polar-moviechart/movie-service:latest
          image: movie-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
#                command: [ "sh", "-c", "sleep 5" ]
                command: [ "sh", "-c", "sleep 3600" ]
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_LOCATION
              value: /workspace/config/application-prod.yml
          volumeMounts:
            - name: movie-config-volume
              mountPath: /workspace/config
      volumes:
        - name: movie-config-volume
          configMap:
            name: movie-config