apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/polar-moviechart/movie-service/k8s?ref=6d4857f500cf3a3d36fcd6257c6c5c9188b2c9db
  - deployment.yml

configMapGenerator:
- name: movie-config
  behavior: merge
  files:
  - application.yml
  options:
    labels:
      app: movie-service

patchesStrategicMerge:
  - patch-regcred.yml
  - patch-env.yml

  # kustomize edit set image 명령어에 의해 변경됨
images:
- name: movie-service
  newName: ghcr.io/polar-moviechart/movie-service
  newTag: 3942bcfedbfe03907a5716591e4a81818520e0fe

replicas:
- count: 1
  name: movie-service
