apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: movie-config
  options:
    labels:
      app: movie-service

patches:
- path: patch-regcred.yml
- path: patch-env.yml

  # kustomize edit set image 명령어에 의해 변경됨
images:
- name: movie-service
  newName: ghcr.io/polar-moviechart/movie-service
  newTag: 932caf8e98e92a06d78229f2c9eb66b708699f29

replicas:
- count: 1
  name: movie-service
