apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

configMapGenerator:
- behavior: create
  files:
  - application-prod.yml
  name: movie-config
  options:
    labels:
      app: movie-service

patches:
- path: patch-regcred.yml
- path: patch-env.yml

  # kustomize edit set image 명령어에 의해 변경됨
images:
- name: movie-service
  newName: ghcr.io/polar-moviechart/movie-service
  newTag: 044d14509306b105383170c873c5e12a54f4a24f

replicas:
- count: 1
  name: movie-service
