apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  template:
    spec:
      containers:
        - name: movie-service
          command: ["slee"]
          args: ["infinity"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod